// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function isLikelySecretKey(key: string): boolean {
  // New Supabase secret keys use this prefix.
  if (key.startsWith('sb_secret_')) return true;

  // Defensive check: if a JWT key payload role is service_role, treat as secret.
  const parts = key.split('.');
  if (parts.length === 3) {
    try {
      const payload = JSON.parse(atob(parts[1]));
      if (payload?.role === 'service_role') return true;
    } catch {
      // Ignore parse errors and continue with other checks.
    }
  }

  return false;
}

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY in environment.');
}

if (isLikelySecretKey(SUPABASE_PUBLISHABLE_KEY)) {
  throw new Error('Refusing to start: a Supabase secret/service-role key was provided to the browser client. Use a publishable/anon key only.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});